Ft project test
freddykaberuka/math-magician pull request #6
Opened 2022-09-15 14:17 UTC by freddykaberuka

## Completed Task

- add test(unit teste of operate.js and calculate.js using jest
- Use Jest snapshots to test the components.
- Use React Testing Library to simulate user interaction.

## ScreenShot
<img width="1719" alt="Screen Shot 2022-09-15 at 07 15 23" src="https://user-images.githubusercontent.com/26603127/190427284-4cadd498-52ce-4a15-a4b5-773ba865f815.png">

2022-09-15 14:36 UTC, danmainah requested changes
Hi @freddykaberuka and @ecekpo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-15 14:36 UTC, danmainah commented on src/components/test/operate.test.js
> +// Test calculation of numbers
- [ ] Kindly add more tests that cover all functionalities & scenarios of the operate.js and calculate.js modules.

2022-09-16 07:48 UTC, sumairq approved these changes
### Hi Team, 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 13:31 UTC, Munsa1 approved these changes

2022-09-23 13:45 UTC, addod19 approved these changes
### Hi TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Git-flow followed :+1: 
- [ ] All test cases passed :1st_place_medal: 


### Optional
- [ ] It would be nice if we add the instructions about how to run the test in our README file since this is a testing project :man_technologist: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 10:06 UTC, merged